### ISSUE TITLE
Ask: What is the email address for?

### ISSUE THREAD

**Issue by inapeace0** [XRPL-Labs/XummPkce#4]
**First of all, thanks for publishing this such good library for XRP Ledger.**
I'm one of XRP lovers and I had some questions while researching about xumm signin.

https://xumm.readme.io/docs/user-sign-in-identity-provider

Through this documentation, I noticed that the email address was unique per the different wallet address and I could get this by a special API with JWT.

1. What's it for?
2. Can I use it as a private key for my private purpose? The wallet address is public, but the email address is private that nobody knows?

Hope enough description about this.
Thanks in advance.

**Comment by WietseWind** [comment]
The virtual email address can not be considered private: it's returned to identity consumers, as you noticed.

The reason for the virtual email address to be returned is explained on the page you're linking to, at the end.

I quote (from that page):

> As some platforms require email address verification by sending a one time code for the user to confirm, after a successful sign in the email address returned by the Xumm OAuth2 platform will allow emails to be received for 10 minutes after the successful login. An email delivered to the unique email address for the specific Xumm App + user (r-address) will be stripped, and served plain text to the end user. The end user will receive a [push notification](https://legyp4b.dlvr.cloud/1.PNG) & [Event](https://jabvmxa.dlvr.cloud/pasted_1.png) in Xumm [serving the email](https://legyp4b.dlvr.cloud/3.PNG). (Links, images, attachments, etc. will be stripped out)

📘
